services:
  backend:
    build: ./Dockerfile_backend
    name: ecommerce-backend
    ports:
      - "5000:5000"
    # Use docker secrets for sensitive information in production instead of environment variables
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_DATABASE=ecommerce_site
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    name: ecommerce-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_site
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./Dockerfile_frontend
    name: ecommerce-frontend
    ports:
      - "3000:80" # Map host port 3000 to Nginx port 80
    depends_on:
      - backend
