export const new_categories = [
  { gender: "Women", category: "Watches", sub_category: "Luxury Watches" },
  { gender: "Women", category: "Watches", sub_category: "Automatic Watches" },
  { gender: "Women", category: "Watches", sub_category: "Vintage Watches" },
  { gender: "Women", category: "Watches", sub_category: "Solar Watches" },
  { gender: "Women", category: "Watches", sub_category: "Aviator Watches" },
  { gender: "Women", category: "Bags", sub_category: "Tote Bags" },
  { gender: "Women", category: "Bags", sub_category: "Satchel Bags" },
  { gender: "Women", category: "Bags", sub_category: "Crossbody Bags" },
  { gender: "Women", category: "Bags", sub_category: "Shoulder Bags" },
  { gender: "Women", category: "Bags", sub_category: "Clutch Bags" },
  { gender: "Women", category: "Bags", sub_category: "Backpacks Bags" },
  { gender: "Women", category: "Wallets", sub_category: "Wristlet" },
  { gender: "Women", category: "Wallets", sub_category: "Clutch" },
  { gender: "Women", category: "Wallets", sub_category: "Bi-fold" },
  { gender: "Women", category: "Wallets", sub_category: "Tri-fold" },
  { gender: "Women", category: "Wallets", sub_category: "Cardholders" },
  { gender: "Women", category: "Wallets", sub_category: "Travel Wallets" },
  { gender: "Men", category: "Watches", sub_category: "Luxury Watches" },
  { gender: "Men", category: "Watches", sub_category: "Automatic Watches" },
  { gender: "Men", category: "Watches", sub_category: "Vintage Watches" },
  { gender: "Men", category: "Watches", sub_category: "Solar Watches" },
  { gender: "Men", category: "Watches", sub_category: "Aviator Watches" },
  { gender: "Men", category: "Bags", sub_category: "Duffel Bags" },
  { gender: "Men", category: "Bags", sub_category: "Sling Bags" },
  { gender: "Men", category: "Bags", sub_category: "Tote Bags" },
  { gender: "Men", category: "Bags", sub_category: "Messenger Bags" },
  { gender: "Men", category: "Bags", sub_category: "Backpacks Bags" },
  { gender: "Men", category: "Wallets", sub_category: "Bi-fold" },
  { gender: "Men", category: "Wallets", sub_category: "Tri-fold" },
  { gender: "Men", category: "Wallets", sub_category: "Cardholders" },
  { gender: "Men", category: "Wallets", sub_category: "Travel Wallets" },
];
